[package]
name = "rng"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
chacha20 = "0.9"
blake3 = "1.5"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
arrayvec = "0.7"
tracing = "0.1"
